### ISSUE TITLE
AP模式没有效果，但Client模式可以搜索连接到无线网络

### ISSUE THREAD

**Issue by pan-rui** [melsem/openwrt-lede_xradio-xr819_soc-audio#1]
![微信截图_20190625223037](https://user-images.githubusercontent.com/7950427/60107661-db818600-9799-11e9-9936-372852bd3895.png)
![微信截图_20190625223108](https://user-images.githubusercontent.com/7950427/60107663-dc1a1c80-9799-11e9-855e-d756aa769452.png)

**Comment by Evilmass** [comment]
先删除现有网卡，然后新建一个AP Clinet，然后再建一个Access Point

**Comment by pan-rui** [comment]
感谢大佬的回复,最近有点忙,有空我再试一下.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Evilmass"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 上午9:54
收件人: "melsem/openwrt-lede_xradio-xr819_soc-audio"<openwrt-lede_xradio-xr819_soc-audio@noreply.github.com&gt;; 
抄送: "潘锐"<79277490@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [melsem/openwrt-lede_xradio-xr819_soc-audio] AP模式没有效果，但Client模式可以搜索连接到无线网络 (#1)




先删除现有网卡，然后新建一个AP Clinet，然后再建一个Access Point

**Comment by chainsx** [comment]
把无线模式改为N能正常使用AP
