### ISSUE TITLE
activate i2c

### ISSUE THREAD

**Issue by antillanca** [melsem/openwrt-lede_xradio-xr819_soc-audio#2]
Dear, do you know how to use i2c in orange pi zero?

**Comment by antillanca** [comment]
&i2c0 {
	status = "okay";
};

&i2c1 {
	status = "okay";
};

&i2c2 {
	status = "okay";
};
 in dts file ;-)

**Comment by melsem** [comment]
> &i2c0 {
> status = "okay";
> };
> 
> &i2c1 {
> status = "okay";
> };
> 
> &i2c2 {
> status = "okay";
> };
> in dts file ;-)
This includes only GPIO.

To use soc-i2c, the i2c-mv64xxx.ko module is used.
And he is not in the packages. [Here I placed the patch on the package to assemble the driver.](https://github.com/openwrt/openwrt/commit/72ef48dd2cbc4f53c4ca293ceb1c1eac4b1c410e#diff-3441e29ce84f55d0bac5e0fb7176407f)

[Here are all the patches.](https://github.com/openwrt/openwrt/compare/master...melsem:master)

Finished Images.
```Included wifi-xr819 and built-in support for soc-audio, SPI NOR, usb2-usb3.
Support sunxi-ir, 1Wire (PA06 gpio-6), i2c0 (SCA-PA11 SDA-PA12).
Support cpufreq-dt, thermal-sunxi (ths).
Edited Thermal Zone for Orange-Zero-LTS.
Info themperature, cpu freq: 192.168.10.1/cgi-bin/modules/about/index.cgi
```
[openwrt-imagebuilder-sunxi-cortexa7.Linux-i686](https://github.com/melsem/openwrt/raw/master/openwrt-imagebuilder-sunxi-cortexa7.Linux-i686.tar.xz)
[orangepi-zero-LTS-ext4](https://github.com/melsem/openwrt/raw/master/openwrt-orangepi-zero-LTS-ext4-sdcard.img.gz)
[orangepi-zero-ext4](https://github.com/melsem/openwrt/raw/master/openwrt-orangepi-zero-ext4-sdcard.img.gz)
